apiVersion: v1
kind: Service
metadata:
  name: qod-web
  labels:
    app: qod-web
    tier: ui
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: qod-web
